version: '3'
services:
  rails:
    build: .
    command: "rm /%app_name%/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/
      - bundle:/%app_name%/vendor/bundle
      - data:/%app_name%/db/data
      - log:/%app_name%/log
    ports:
      - '3000:3000'
      - '1234:1234'
    environment:
      POSTGRES_PASSWORD: example
    depends_on:
      - db
      - redis
    tty: true
  db:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: "%app_name%_development"
  redis:
    image: redis:4

volumes:
  bundle:
  data:
  log:
