version: '3'
services:
  rails:
    build: .
    command: bin/rails s -p 3000 -b '0.0.0.0' -e development
    volumes:
      - .:/%app_name%
      - data:/%app_name%/db/data
      - log:/%app_name%/log
    ports:
      - '3000:3000'
      - '1234:1234'
    environment:
      MYSQL_PASSWORD: example
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: "%app_name%_development"
      MYSQL_USER: mysql
      MYSQL_PASSWORD: example
    tty: true
  redis:
    image: redis:4
    tty: true

volumes:
  bundle:
  data:
  log:
