version: '3'
services:
  rails:
    build: .
    command: bin/rails s -p 3000 -b '0.0.0.0' -e development
    volumes:
      - .:/%app_name%
      - data:/%app_name%/db/data
      - log:/%app_name%/log
    ports:
      - '3000:3000'
      - '1234:1234'
    environment:
      POSTGRES_PASSWORD: example
      COMPOSE_HTTP_TIMEOUT=90
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true
  db:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: "%app_name%_development"
    tty: true
  redis:
    image: redis:4
    tty: true

volumes:
  bundle:
  data:
  log:
