version: '3'
services:
  rails:
    build: .
    command: /bin/sh -c "rm -f /rails/tmp/pids/server.pid && (bundle check || bundle install) && bin/rails s -b '0.0.0.0' -e development"
    volumes:
      - .:/rails
      - gems:/bundle
      - tmp:/rails/tmp
    ports:
      - '3000:3000'
      - '3035:3035'
      - '1234:1234'
    environment:
      MYSQL_USERNAME: mysql
      MYSQL_PASSWORD: example
    env_file: .env
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: "%app_name%_development"
      MYSQL_USER: mysql
      MYSQL_PASSWORD: example
    volumes:
      - mysql-data:/var/lib/mysql
    tty: true
  redis:
    image: redis:4
    tty: true
volumes:
  gems:
  mysql-data:
  tmp:
