version: '3'
services:
  rails:
    build: .
    command: /bin/sh -c "rm -f /rails/tmp/pids/server.pid && (bundle check || bundle install) && bin/rails s -b '0.0.0.0' -e development"
    volumes:
      - .:/rails
      - gems:/bundle
      - tmp:/rails/tmp
    ports:
      - '3000:3000'
      - '3035:3035'
      - '1234:1234'
    env_file: .env
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true
  db:
    image: mongo:3.6
    volumes:
      - "mongo-data:/var/lig/mongo"
    tty: true
  redis:
    image: redis:4
    tty: true
volumes:
  gems:
  mongo-data:
  tmp:
