default: &default
  adapter: mysql2
  encoding: utf8
  host: db
  password: <%= ENV.fetch("MYSQL_PASSWORD") %>
  username: root
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: %app_name%_development

test:
  <<: *default
  database: %app_name%_test
